### ISSUE TITLE
Can you run this example code with a newer global version of Angular CLI?

### ISSUE THREAD

**Issue by dauledk** [anihalaney/rwa-trivia#26]

**Comment by anihalaney** [comment]
I haven't tested with the latest version of the cli, but it should work as long as cli's global version is same as the cli in the project. The cli versions of global & local must be same.
I will be upgrading to the latest this weekend, though. So, I'll find out soon.

**Comment by anihalaney** [comment]
Commit: dc2fdb2 - Upgraded to latest versions of cli, angular, angular-material and ngrx (4)
