### ISSUE TITLE
error when deploying functions

### ISSUE THREAD

**Issue by cissecedric** [anihalaney/rwa-trivia#39]
Hi Anihalaney and TY for your great job,

I have en error when I try to deploy cloud functions:
Error parsing triggers: Cannot find module './server/functions/app'

Do you have any idea ?
Regards

**Comment by anihalaney** [comment]
did the typescript compile the functions ok?
the `tsc --project functions` should compile the functions and put the output JS files in the above folder.
The `npm run deploy-functions` should be able to cleanup folder, compile and deploy it to firebase.

**Comment by cissecedric** [comment]
TY @anihalaney you have solved my problem, i'm now struggling with the gcloud compute-ssh command (error 255) but that's another story!
Regards,
