### ISSUE TITLE
errors with gcloud functions

### ISSUE THREAD

**Issue by cissecedric** [anihalaney/rwa-trivia#40]
Hi Ashkay,

Thank you for your help so far, your project is exactly what I'am trying to do.
 I finally succeed to set up the Elasticsearch & Nginx part... and I am now trying to run the master version, I followed the getting started, but I have several problems, maybe could you help me to solve some of them?

In my gcloud console I can see several errors and among them these ones:
* No Firebase ID token was passed as a Bearer token in the Authorization header. Make sure you authorize your request by providing the following HTTP header: Authorization: Bearer <Firebase ID Token> or by passing a "__session" cookie.

*Trace: [index_not_found_exception] no such index, with { resource.type="index_or_alias" & resource.id="questions" & index_uuid="_na_" & index="questions" } at /user_code/server/functions/ESUtils.js:238:21 at process._tickDomainCallback (internal/process/next_tick.js:135:7)

And in my web client (chrome)
* GET https://us-central1-xxxxxxx.cloudfunctions.net/app/getQuestionOfTheDay 500 ()

* Failed to load https://us-central1-xxxxxxx.cloudfunctions.net/app/getQuestionOfTheDay: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://localhost:4200' is therefore not allowed access. The response had HTTP status code 500.

* Effect "QuestionEffects.loadSampleQuestions$" threw an error
effects.es5.js:247 Source: QuestionEffects {actions$: Actions, questionActions: QuestionActions, svc: QuestionService, loadQuestions$: Actions, loadUnpublishedQuestions$: Actions, …}

**Comment by anihalaney** [comment]
The readme is a bit outdated and hasn't been updated in a while. I'll try to update it this weekend.

Did you build the elasticsearch question index?  There is a "rebuild_questions_index" api that builds out the index. However, this api needs authentication. I would comment out the authentication part and rebuild the index. (I'm assuming you have some questions already in the firestore db)

**Comment by cissecedric** [comment]
Thank you very much for your answer, it's OK now.
I've commented authentication part in gcloud functions and run the migration function with postman,
built the elasticsearch index,
and finally uncomment authentication.
