### ISSUE TITLE
Users et roles

### ISSUE THREAD

**Issue by cissecedric** [anihalaney/rwa-trivia#41]
Hi,
It seems that users are not stored in rtdb nor firestore, but we have a 
getUserRoles method that fetch in users collection in authentication.service.
Maybe is it planned in the futur to add users in this collection when they sign up ?

Regards,

**Comment by anihalaney** [comment]
the only user role stored in rtdb (and now firestore) is the admin role.
the user role is not stored, just assumed to be a regular user if a role is not found.
you need to add the admin role manually to the database.

**Comment by cissecedric** [comment]
Ok , I found how to store the users,  thx ;-)
